# Generated by Django 4.1.5 on 2023-01-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0002_alter_url_short_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='ShortUrl',
        ),
    ]
