# Generated by Django 4.1.5 on 2023-01-31 20:36

from django.db import migrations


def create_short_urls(apps, schema_editor):
    links = ['https://reddit.com',
             'https://linkedin.com', 'https://facebook.com']
    codes = ['Av32eEa', 'Ea214gR', 'Lg3e5r2']
    ShortUrl = apps.get_model('shortUrl', 'ShortUrl')
    for i in range(len(links)):
        new_short = ShortUrl(original_url=links[i], short_code=codes[i])
        new_short.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0003_rename_url_shorturl'),
    ]

    operations = [
        migrations.RunPython(create_short_urls),
    ]
