# Generated by Django 4.1.5 on 2023-02-02 05:55

from django.db import migrations, models
import shortUrl.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0004_auto_20230131_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.TextField(validators=[shortUrl.models.validate_url]),
        ),
    ]
